### ISSUE TITLE
Add global configuration options.

### ISSUE THREAD

**Issue by beauby** [jsonapi-rb/jsonapi-rails#10]
- [ ] Opt-out of renderer registration (for instance when using deserialization only).
- [ ] Opt-in for top level `jsonapi` member.
- [ ] Global custom serializable resource class inferrer.
- [ ] ...?

**Comment by dush** [comment]
It would be nice to be able to define handlers for parser exceptions like JSON::ParserError, JSONAPI::Parser::InvalidDocument. Such handler could return status 4xx (client error) possibly with jsonapi errors object instead of default 500 response.

**Comment by beauby** [comment]
@dush Sorry for the late reply – you can already do the following in your controllers:
```ruby
rescue_from JSONAPI::Parser::InvalidDocument do |exception|
  head 400
end
```
