### ISSUE TITLE
Remove log message

### ISSUE THREAD

**Issue by wee007** [jsonapi-rb/jsonapi-rails#116]
Is there a way to remove this log message apart from a monkey patch?

`INFO -- : Completed JSON API rendering`

I've tried unsubscribing the subscriber and detaching the namespace but to no avail.

**Comment by raldred** [comment]
Agreed, they're really noisy and should be moved to debug

**Comment by raldred** [comment]
@wee007 Only way I could find to do this was to unsubscribe the instrumentation in an initializer

```
# config/initializers/jsonapi-rails.rb
ActiveSupport::Notifications.unsubscribe('parse.jsonapi-rails')
ActiveSupport::Notifications.unsubscribe('render.jsonapi-rails')
```

**Comment by wee007** [comment]
Thanks heaps @raldred ! That worked.

**Comment by ndbroadbent** [comment]
I just ran into this issue. I fixed it by adding this to `spec/rails_helper.rb`:

```
ActiveSupport.on_load(:action_controller) do
  ActiveSupport::Notifications.unsubscribe('parse.jsonapi-rails')
  ActiveSupport::Notifications.unsubscribe('render.jsonapi-rails')
end
```
