### ISSUE TITLE
Incomatible with rails 6

### ISSUE THREAD

**Issue by shushugah** [jsonapi-rb/jsonapi-rails#117]
Thank you for the open source work you have done with this gem!

I am upgrading my rails version to 6, and am using `jsonapi_resources` which is dependency on this gem, which is dependent on Rails 5. Is there any plans to support Rails 6 or alternative solutions?

**Comment by addywaddy** [comment]
It's just a development dependency, so will work with  rails 6. There are deprecation warnings caused by https://github.com/jsonapi-rb/jsonapi-rails/blob/master/lib/jsonapi/rails/railtie.rb#L55. These can be silenced in your app by setting the following in e.g. `application.rb`:

```ruby
config.action_dispatch.return_only_media_type_on_content_type = false
```
