### ISSUE TITLE
Still maintained? Need help?

### ISSUE THREAD

**Issue by tagliala** [jsonapi-rb/jsonapi-rails#146]
Hello, I may use this library in a Rails application and at the moment I can provide some contribution

I'm interested in merging
- #141
- #143
- #144
- #145

and eventually release a new version with MFA enabled

**Comment by tagliala** [comment]
Hello

- #152

 Are you interested in dropping all legacy RoR and Ruby versions?
 
 That would mean Ruby < 3.1 and Rails < 7.0 (6.1 support will end in 13 days)

**Comment by beauby** [comment]
Cc. @remear

**Comment by tagliala** [comment]
PR updated to remove all EOL rails and ruby versions. 6.1 just ended its security support
