### ISSUE TITLE
Deserialization does not work in Rails controller specs.

### ISSUE THREAD

**Issue by cilim** [jsonapi-rb/jsonapi-rails#18]
_Issue moved from [jsonapi-parser](https://github.com/jsonapi-rb/jsonapi-parser/issues/5)_

I'm trying to use the [jsonapi-rails](https://github.com/jsonapi-rb/jsonapi-rails) gem to deserialize the incoming params on an HTTP request, but it's not working as expected.

I tried 2 approaches:

Firstly I followed the instructions from [the guides](http://jsonapi-rb.org/guides/deserialization/deserializing.html) and tried using the default `JSONAPI::Deserializable::Resource.call(json_hash)` like this:

```ruby
class AuthorsController < ApplicationController
  def create
    respond_with Author.create(author_params), class: AuthorSerializer
  end

  private

  def author_params
    JSONAPI::Deserializable::Resource.call(params)  
  end
```

but since the [JSONAPI::Parser::Resource](https://github.com/jsonapi-rb/jsonapi-parser/blob/master/lib/jsonapi/parser/resource.rb) is expecting a hash an error is raised.

The second approach is using the `deserializable_resource` on the controller level:

```ruby
class AuthorsController < ApplicationController
  deserializable_resource :author, only: :create
  
  def create
    respond_with Author.create(author_params), class: AuthorSerializer
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
```

When I try it like this I get `ActionController::ParameterMissing: param is missing or the value is empty: author` when inspecting the `author_params`. If I inspect the `params` they are looking like this:

```
ActionController::Parameters {"data"=>{"type"=>"authors", "attributes"=>{"name"=>"Author name"}}, "controller"=>"api/v1/authors", "action"=>"create"} permitted: false>
```

which means that the desiralization on the params didn't occur.

Any guidance would be helpful. I'm using ruby 2.3.1p112 and Rails 5.0.1

**Comment by beauby** [comment]
Hi, sorry for the late reply! The second approach is definitely the right one when using rails. Could you post an actual JSON payload that triggers this behavior?

**Comment by cilim** [comment]
Sure...it's the one that's in the params described above:

```
{
  "data" => {
    "type" => 'authors',
    "attributes" => {
      "name" => "Author name"
    }
  }
}
```

**Comment by beauby** [comment]
I just tested the following:
```ruby
class AuthorsController < ActionController::Base
  deserializable_resource :author, only: [:create]

  def create
    render json: author_params
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
end
```

and it works fine (with your payload, it replies with `{ "name": "Author name" }`.

**Make sure your POST request has the `Content-Type` header set to `application/vnd.api+json`**

**Comment by cilim** [comment]
Thats odd...can you please paste me your specs too and what version of Ruby and Rails you're using?

**Comment by beauby** [comment]
```ruby
RSpec.describe 'Basic CRUD', type: :request do
  it 'works' do
    params =
      {
       	"data" => {
          "type" => 'authors',
          "attributes" => {
            "name" => "Author name"
          }
	}
      }
    post '/authors',
         params: params,
         as: :json,
         headers: { 'CONTENT_TYPE' => 'application/vnd.api+json' }

    p response.body
    # => { "name": "Author name" }
  end
end
```

**Comment by cilim** [comment]
I confirm that the request specs work properly, but what about controller specs?

**Comment by beauby** [comment]
@cilim Right, so controller specs do not execute the whole stack, but only the controller itself, which causes rack middlewares not to be executed (among which deserialization, as well as authentication in case you use a warden-based solution).
So your options are 1. provide the controller with already deserialized parameters or 2. avoid controller specs altogether (I find they add very little value compared to request specs, but I'd love to hear your take on it).

**Comment by cilim** [comment]
I needed to test a single HTTP request in each example so I thought controller specs would be better, but I found a workaround with request specs.

Thank you very much for your help!
