### ISSUE TITLE
jsonapi-rails/jsonapi-rb incompatibility

### ISSUE THREAD

**Issue by klobuczek** [jsonapi-rb/jsonapi-rails#45]
jsonapi-rails 0.2.1 is not version compatible with jsonapi-rb 0.3.0, while
jsonapi-rails 0.1.2 is. I don't think this is intended. It causes very strange bundler version resolution.

**Comment by beauby** [comment]
Thanks for pointing this out @klobuczek. Looking into it right now.

**Comment by beauby** [comment]
This will be fixed in the next release of jsonapi-rails.

**Comment by beauby** [comment]
Dependencies are now strictly pinned until 1.0 release, so this shouldn't be an issue anymore. Thanks @klobuczek!
