### ISSUE TITLE
Using "preloader" to load associations based on "include"

### ISSUE THREAD

**Issue by TheRusskiy** [jsonapi-rb/jsonapi-rails#62]
Is this already implemented?
If not, then do you see any roadblocks in doing so?
Thank you :-)

**Comment by beauby** [comment]
Hi TheRusskiy – I'm thinking about providing a pre-rendering hook so that people could override it as follows:
def jsonapi_resources(resources)
  resources.include(jsonapi_include) if # resources is an activerecord query
end

What do you think?

**Comment by TheRusskiy** [comment]
@beauby great idea, would make it a more universal solution.
