### ISSUE TITLE
Render error code

### ISSUE THREAD

**Issue by arefaslani** [jsonapi-rb/jsonapi-rails#64]
I want to render error `code` property, as JSON API specification describes, with `jsonapi_errors` method. How could I set the code property in error object?

**Comment by beauby** [comment]
Hi @arefaslani. It really depends how you're serializing your errors. If you're using custom error serializers, you can use the `code` DSL method.

**Comment by arefaslani** [comment]
How should I use the `code` DSL? I tested it as:
```ruby
render jsonapi_errors: outcome.errors, code: 100, status: :unprocessable_entity
```
but it doesn't work.
I use ActiveInteraction as the I in DCI. This is my configuration for jsonapi:
```ruby
JSONAPI::Rails.configure do |config|
  # Set a default serializable class mapping for errors.
  config.jsonapi_errors_class = Hash.new { |h, k|
  }.tap { |h|
    h[:'ActiveModel::Errors'] = JSONAPI::Rails::SerializableActiveModelErrors
    h[:'ActiveInteraction::Errors'] = JSONAPI::Rails::SerializableActiveModelErrors
    h[:Hash] = JSONAPI::Rails::SerializableErrorHash
  }
end
```
[Here](http://jsonapi.org/format/#error-objects) is  how JSON API describes error code.

**Comment by arefaslani** [comment]
@beauby I can't find code DSL and how to use it anywhere...
