### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by sumancc** [jsonapi-rb/jsonapi-rails#65]
Hi, 
Great work on this gem. I am waiting for the next release which has the hook for 'meta'. Any idea when the next release would be? And if there can any help in getting the next release out, I am happy to help.
thanks!

**Comment by beauby** [comment]
Hi @sumancc. Thanks! I was rather busy lately but hopefully I'll be able to cut a new release over the next week. Don't hesitate to ping me if this flies of my radar.

**Comment by blmundie** [comment]
Any update on the next release?

**Comment by d4be4st** [comment]
Any update on the next release? 

Also in need of 'meta' key

**Comment by saravanak** [comment]
I too have the same issue, figured out that `meta` hook is missing from the gem version. Worked around by installing from `git master`.

**Comment by dawidof** [comment]
@beauby Is there any news on the next release?

**Comment by baxang** [comment]
First thanks for writing this gem. It has been super helpful. Can we please have a new release? The lack of https://github.com/jsonapi-rb/jsonapi-rails/commit/6d49925aedb08c34d9891916fd5936e6697ba9d6 makes this awesome gem doesn't work in Rails >= 5 without patching for two years. A release of 0.4.1 would be really nice. @beauby

**Comment by remear** [comment]
v0.4.1 has been released.
