### ISSUE TITLE
undefined method `new' for nil:NilClass

### ISSUE THREAD

**Issue by nleo** [jsonapi-rb/jsonapi-rails#74]
class Api::V1::CitiesController < ApplicationController
      def index
        render jsonapi: City.limit(10).all,
          jsonapi_class: 'Api::V1::SerializableCity'
      end
    end

    # cat app/serializers/api/v1/serializable_city.rb
    class Api::V1::SerializableCity < JSONAPI::Serializable::Resource
      type 'cities'
      attributes :code, :name_ru, :name_en
      # has_many :airports
    end
<details>
  <summary>Full Trace:</summary>

    jsonapi-serializable (0.3.0) lib/jsonapi/serializable/renderer.rb:89:in `_build'
    jsonapi-serializable (0.3.0) lib/jsonapi/serializable/renderer.rb:80:in `block in build_resources'
    jsonapi-serializable (0.3.0) lib/jsonapi/serializable/renderer.rb:80:in `map'
    jsonapi-serializable (0.3.0) lib/jsonapi/serializable/renderer.rb:80:in `build_resources'
    jsonapi-serializable (0.3.0) lib/jsonapi/serializable/renderer.rb:44:in `render'
    jsonapi-rails (0.3.1) lib/jsonapi/rails/renderer.rb:16:in `render'
    jsonapi-rails (0.3.1) lib/jsonapi/rails/railtie.rb:58:in `block (4 levels) in register_renderers'
    activesupport (5.1.4) lib/active_support/notifications.rb:168:in `instrument'
    jsonapi-rails (0.3.1) lib/jsonapi/rails/railtie.rb:55:in `block (3 levels) in register_renderers'
    actionpack (5.1.4) lib/action_controller/metal/renderers.rb:149:in `block in _render_to_body_with_renderer'
    /usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
    /usr/lib/ruby/2.3.0/set.rb:306:in `each'
    actionpack (5.1.4) lib/action_controller/metal/renderers.rb:145:in `_render_to_body_with_renderer'
    actionpack (5.1.4) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
    actionpack (5.1.4) lib/abstract_controller/rendering.rb:24:in `render'
    actionpack (5.1.4) lib/action_controller/metal/rendering.rb:36:in `render'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
    activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
    /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
    activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
    activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
    app/controllers/api/v1/cities_controller.rb:4:in `index'
    actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
    actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
    actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
    activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
    activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
    actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
    actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
    actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
    actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
    actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
    actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
    actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
    actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
    actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
    actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
    rack (2.0.3) lib/rack/etag.rb:25:in `call'
    rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
    rack (2.0.3) lib/rack/head.rb:12:in `call'
    rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
    rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
    activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
    activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
    actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
    web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
    web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
    web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
    web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
    railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
    activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
    activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
    railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
    sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
    rack (2.0.3) lib/rack/method_override.rb:22:in `call'
    rack (2.0.3) lib/rack/runtime.rb:22:in `call'
    activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
    rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
    rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
    railties (5.1.4) lib/rails/engine.rb:522:in `call'
    puma (3.11.0) lib/puma/configuration.rb:225:in `call'
    puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
    puma (3.11.0) lib/puma/server.rb:438:in `process_client'
    puma (3.11.0) lib/puma/server.rb:302:in `block in run'
    puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

</details>

**Comment by beauby** [comment]
Hi @nleo – `jsonapi_class: 'Api::V1::SerializableCity'` should probably be `class: { City: Api::V1::SerializableCity }`.
The `render` method takes a `class` parameter, the value of which is a hash or lambda mapping model classes to serializer classes.
Closing this, but feel free to comment if you need more help.

**Comment by nleo** [comment]
Ok, thank you. I have read this http://jsonapi-rb.org/guides/getting_started/rails.html skipping this http://jsonapi-rb.org/guides/getting_started/plain_ruby.html . But when I returned to http://jsonapi-rb.org/guides/getting_started/plain_ruby.html I figure out this feature `class: { Post: SerializablePost, User: SerializableUser, Comment: SerializableComment },`

So I think it's unclear documentation issue

**Comment by skunkworker** [comment]
I ran into this same issue with a namespaced model object and the documentation wasn't clear about how to set the serializer for it.

I had a namepaced model object like
`Foo::Bar`
 and I ended up having to write 
`render jsonapi: user.foo_bars, class: { :"Foo::Bar" => SerializableFooBar }`

But this succeeded.

**Comment by corroded** [comment]
I think the above needs to be in the README. I came across this as well and the error messages weren't that helpful.

**Comment by basti** [comment]
You get the same exact message when you have a single-table inheritance (STI) model. For example, if you have `User`, `Admin < User`, and `Customer < User` you have to specify class to be used for serialization for each STI class (i.e. it won't just assume that it can use `SerializableUser`).

```ruby
users = User.all
render jsonapi: users, class: { Manager: SerializableUser, Resident: SerializableUser }
```
