### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by GeorgeKaraszi** [jsonapi-rb/jsonapi-rails#77]
Sorry for raising this as a new issue (wish Github had a discussion board or something). 

I was wondering, with the Rails cache fix in the `json-caching` branch. If we could expect a new release? I try my best to avoid referencing Github branches directly whenever I can.

This is also a callout for a new release for the `json-render` gem (which I guess would need to be included regardless).

**Comment by beauby** [comment]
Apologies for the time this is taking. I'll try to set aside some time this week.

**Comment by benbarber** [comment]
Any update on when we can expect a release that includes the caching fix?

**Comment by GeorgeKaraszi** [comment]
Hate to continuously nag on this thing. But is a release coming soon?
