### ISSUE TITLE
Compare with JSONAPI::Resources

### ISSUE THREAD

**Issue by pmackay** [jsonapi-rb/jsonapi-rails#81]
It would be useful to have something in the docs describing the motivation behind this project and how it differs from similar libraries like http://jsonapi-resources.com/.

**Comment by beauby** [comment]
Agreed. I have little bandwidth at the moment, so any PR would be much welcome, but bottom line is that jsonapi-resources takes over your controllers whereas this library is focused on serialization/deserialization of resources.
