### ISSUE TITLE
no json/jsonb support?

### ISSUE THREAD

**Issue by JerryGreen** [jsonapi-rb/jsonapi-rails#84]
For render method I can use something like this (example from official doc):

```ruby
           fields: { users: [:name, :email], posts: [:title, :content] }
```

But I can't use this, right?

```ruby
           fields: { users: [:name, :email], posts: [:title, :content, data: [:additional_info, :some_key]] }
```

Why? I want that filtering for json/jsonb columns ;(

**Comment by beauby** [comment]
A bit late but: the reason is simply that the json:api spec does not allow the above to be expressed via the `fields` query parameter. You could do multiple serializers.
