### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by caseyprovost** [jsonapi-rb/jsonapi-rails#88]
I have noticed master has diverged quite a lot from 0.3.1. Are you close to being able to release the new merges and refactors?

**Comment by remear** [comment]
@beauby A quick ping on this.

**Comment by crescentrose** [comment]
@beauby Any news on a new release?

**Comment by caseyprovost** [comment]
@jkeen @remear @crescentrose check out https://graphiti-api.github.io/graphiti/guides. I have moved onto this library because it has a few more necessary features like side-posting, side-loading, first-class support for sorting, etc. Highly recommend

**Comment by remear** [comment]
I’d be interested to hear others’ thoughts on this library vs graphiti vs 
https://github.com/Netflix/fast_jsonapi
