### ISSUE TITLE
passing current_user to Serializable class

### ISSUE THREAD

**Issue by csaurav** [jsonapi-rb/jsonapi-rails#89]
Hi, 

I have to show some attribute, based on the user role and for this matter, I have to pass current_user object to the SerializableMyClass. 

How to do it ?

Thanks

**Comment by beauby** [comment]
In your render call, you can specify an `expose` parameter, which allows you to expose arbitrary variables to serializable classes.

Example:
```ruby
roles = { lucas: :admin }
render jsonapi: users, expose: { roles: roles }
```

Then you can refer to exposed parameters as instance variables in the serializable classes: e.g. `@roles`.
