### ISSUE TITLE
Take the guesswork out of resolving missing serializer errors?

### ISSUE THREAD

**Issue by MrLeebo** [jsonapi-rb/jsonapi-rails#91]
If you misconfigure your `class` option, you're greeted with `undefined method 'new' for nil:NilClass`. I understand why this error occurs, but for a complex graph, it can be difficult to figure out which serializer it tried to construct.

Seems like it would be possible to print the expected name of the class in the error message like instead:

```
Invalid serializer [SerializableUser]
```

**Comment by JoeWoodward** [comment]
This issue is actually related to https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable.rb and as you can see has already been fixed. The jsonapi-rails gem hasn't been updated yet
